# Site settings
title: CoinCloi
product: Cashflow
email: support@coincloi.com
url: https://www.coincloin.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
slogan: "Coming soon in  App Store"
meta_author: Will Zhang

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static
formspree: https://formspree.io/f/mbjvqdyg

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fec830 #header background
  primary-rgb: "254,200,48" #mask
  secondary: 333333 #nav background
  secondary-dark: fec830 #footer background

# Footer settings
footer:
  copyright: CoinCloi
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/CoinCloi/www.coincloi.com

# Postal address (add as many lines as necessary)
address:
  - line: 4 Xinyu Road, Changning
  - line: 200050 Shanghai
  - line: China

# Credits content
credits: 'This website is built upon Freelancer, which is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# About
about: 
  p1: CoinCloi is all about managing your money smarter. Our app, Cashflow, lets you see your financial picture clearly by tracking your income, expenses, assets, and liabilities. 
  p2: What sets Cashflow apart is its use of ideas from 'Rich Dad Poor Dad', showing how passive income covering expenses can lead to financial freedom. It highlights your progress toward financial freedom, keeping you motivated and focused.

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
